### ISSUE TITLE
alpine?

### ISSUE THREAD

**Issue by johnjelinek** [tianon/docker-syncthing#1]
FYI -- https://github.com/syncthing/syncthing/issues/2555. Want to change to alpine instead of ubuntu to make the image size super small? I can if you don't want to.

**Comment by tianon** [comment]
Oooh, super interesting; does that mean 0.12.8 was fully static, or that
0.12.9 will be?

**Comment by tianon** [comment]
Oh baller:

``` console
$ docker run -it --rm tianon/syncthing bash
user@9843ab01628f:/$ ldd /usr/local/bin/syncthing
    not a dynamic executable
```

**Comment by tianon** [comment]
Ok, updating!  :metal:

**Comment by johnjelinek** [comment]
@tianon: lemme know when I can pull latest from docker hub.

**Comment by tianon** [comment]
Yeah, I'm setting up some local CI and using this to work out the kinks --
should be pushed now! :smile:

**Comment by johnjelinek** [comment]
thx!
