### ISSUE TITLE
a wiki maybe or a better readme ?

### ISSUE THREAD

**Issue by changemenemo** [tianon/docker-syncthing#4]
How did you organise your configuration system and where are the default data structure?

**Comment by tianon** [comment]
See https://github.com/tianon/docker-syncthing/blob/b1f8998c548aafd9d430298e70b79d50e3bd5ce8/run.sh#L16-L19 for where data gets mounted in the container (by default, `syncthing` stores configuration in `~/.config/syncthing`).

See https://docs.syncthing.net/users/config.html for more information about the default configuration. :+1:

**Comment by tianon** [comment]
(To be more precise, https://github.com/infosiftr/hocker/blob/2c7a364f367312c4b03fc4ffbda00781e0cb9948/example/syncthing is the script I'm using these days to launch `syncthing`, but it's still very similar to the `run.sh` included in this repo.)
